/**
 * levels.js — 20 màn Laser Maze 404 (module JS thuần).
 *
 * fixed: ["source",x,y,dir] · ["receiver",x,y,màu] · ["mirror",x,y,o]
 *        ["splitter",x,y,o] · ["filter",x,y,màu] · ["blocker",x,y]
 * solution: [[x,y,o]] — xoay gương cố định hoặc đặt gương mới (kho).
 * mirrors: giới hạn gương người chơi được đặt.
 * Mọi lời giải được unit test kiểm chứng (expansion11.test.mjs).
 */

export const LEVELS = [
  {
    id: 1,
    name: "TIA ĐẦU TIÊN",
    w: 7,
    h: 6,
    mirrors: 1,
    intro: "Đặt gương chéo để bẻ tia laser đỏ lên bộ thu. Nhấp ô trống để đặt gương, nhấp lần nữa để xoay hoặc gỡ.",
    fixed: [
      ["source", 0, 3, "R"],
      ["receiver", 5, 0, "red"],
    ],
    solution: [[5, 3, "/"]],
  },
  {
    id: 2,
    name: "HAI KHÚC CUA",
    w: 7,
    h: 6,
    mirrors: 2,
    intro: "Hai gương — hai khúc cua. Dẫn tia qua góc chữ Z tới bộ thu.",
    fixed: [
      ["source", 0, 4, "R"],
      ["receiver", 6, 1, "red"],
      ["blocker", 5, 4],
    ],
    solution: [
      [3, 4, "/"],
      [3, 1, "/"],
    ],
  },
  {
    id: 3,
    name: "XOAY GƯƠNG",
    w: 7,
    h: 6,
    mirrors: 0,
    intro: "Không có gương trong kho — hai gương trên board đang xoay SAI hướng. Nhấp để xoay chúng.",
    fixed: [
      ["source", 0, 3, "R"],
      ["receiver", 6, 1, "red"],
      ["mirror", 2, 3, "\\"],
      ["mirror", 2, 1, "\\"],
      ["blocker", 4, 4],
    ],
    solution: [
      [2, 3, "/"],
      [2, 1, "/"],
    ],
  },
  {
    id: 4,
    name: "KHE HẸP",
    w: 8,
    h: 6,
    mirrors: 3,
    intro: "Bức tường chặn chỉ hở một khe dưới đáy. Luồn tia qua khe rồi vòng lên bộ thu.",
    fixed: [
      ["source", 0, 2, "R"],
      ["receiver", 6, 0, "red"],
      ["blocker", 4, 0],
      ["blocker", 4, 1],
      ["blocker", 4, 2],
      ["blocker", 4, 3],
      ["blocker", 4, 4],
    ],
    solution: [
      [2, 2, "\\"],
      [2, 5, "\\"],
      [6, 5, "/"],
    ],
  },
  {
    id: 5,
    name: "TÁCH ĐÔI",
    w: 8,
    h: 7,
    mirrors: 2,
    intro: "Bộ tách chùm chia tia thành 2 hướng: đi thẳng và phản xạ. Dẫn CẢ HAI nhánh về bộ thu.",
    fixed: [
      ["source", 0, 3, "R"],
      ["splitter", 4, 3, "\\"],
      ["receiver", 5, 0, "red"],
      ["receiver", 1, 5, "red"],
    ],
    solution: [
      [5, 3, "/"],
      [4, 5, "/"],
    ],
  },
  {
    id: 6,
    name: "KÍNH LỌC XANH",
    w: 8,
    h: 7,
    mirrors: 1,
    intro: "Bộ thu XANH chỉ nhận tia xanh. Cho tia đỏ xuyên qua kính lọc để nhuộm màu trước khi tới đích.",
    fixed: [
      ["source", 0, 2, "R"],
      ["filter", 4, 2, "cyan"],
      ["receiver", 6, 5, "cyan"],
      ["blocker", 7, 2],
    ],
    solution: [[6, 2, "\\"]],
  },
  {
    id: 7,
    name: "HAI MÀU",
    w: 9,
    h: 7,
    mirrors: 1,
    intro: "Một nguồn — hai bộ thu khác màu. Tách tia rồi cho mỗi nhánh xuyên đúng kính lọc.",
    fixed: [
      ["source", 0, 3, "R"],
      ["splitter", 3, 3, "\\"],
      ["filter", 6, 3, "cyan"],
      ["receiver", 8, 3, "cyan"],
      ["filter", 5, 5, "violet"],
      ["receiver", 8, 5, "violet"],
      ["blocker", 3, 6],
    ],
    solution: [[3, 5, "\\"]],
  },
  {
    id: 8,
    name: "MÊ CUNG CHẶN",
    w: 9,
    h: 7,
    mirrors: 4,
    intro: "Các khối chặn giăng kín lối đi thẳng. Lách tia qua 4 khúc cua để về đích.",
    fixed: [
      ["source", 0, 1, "R"],
      ["receiver", 8, 5, "red"],
      ["blocker", 6, 1],
      ["blocker", 4, 4],
      ["blocker", 8, 3],
      ["blocker", 2, 5],
      ["blocker", 1, 3],
    ],
    solution: [
      [4, 1, "\\"],
      [4, 3, "\\"],
      [7, 3, "\\"],
      [7, 5, "\\"],
    ],
  },
  {
    id: 9,
    name: "NHÀ GƯƠNG",
    w: 9,
    h: 8,
    mirrors: 2,
    intro: "Kết hợp: xoay 2 gương có sẵn cho đúng hướng, rồi đặt thêm 2 gương từ kho để hoàn tất đường tia.",
    fixed: [
      ["source", 0, 6, "R"],
      ["receiver", 8, 0, "red"],
      ["mirror", 4, 6, "\\"],
      ["mirror", 4, 2, "\\"],
      ["blocker", 8, 2],
      ["blocker", 3, 4],
    ],
    solution: [
      [4, 6, "/"],
      [4, 2, "/"],
      [7, 2, "/"],
      [7, 0, "/"],
    ],
  },
  {
    id: 10,
    name: "HAI NGUỒN",
    w: 10,
    h: 8,
    mirrors: 4,
    intro: "Hai nguồn laser bắn ngược chiều nhau. Dẫn mỗi tia về đúng bộ thu của nó.",
    fixed: [
      ["source", 0, 2, "R"],
      ["source", 9, 5, "L"],
      ["receiver", 9, 0, "red"],
      ["receiver", 0, 7, "red"],
      ["blocker", 4, 4],
      ["blocker", 6, 6],
    ],
    solution: [
      [7, 2, "/"],
      [7, 0, "/"],
      [2, 5, "/"],
      [2, 7, "/"],
    ],
  },
  {
    id: 11,
    name: "LỌC KÉP",
    w: 10,
    h: 8,
    mirrors: 1,
    intro: "Kính lọc cùng màu cho tia đi tiếp, khác màu sẽ CHẶN. Quan sát kỹ trước khi tách nhánh.",
    fixed: [
      ["source", 0, 4, "R"],
      ["splitter", 2, 4, "\\"],
      ["filter", 3, 4, "cyan"],
      ["filter", 6, 4, "cyan"],
      ["receiver", 9, 4, "cyan"],
      ["filter", 2, 6, "violet"],
      ["receiver", 9, 7, "violet"],
      ["blocker", 5, 6],
    ],
    solution: [[2, 7, "\\"]],
  },
  {
    id: 12,
    name: "ĐƯỜNG VÒNG",
    w: 10,
    h: 9,
    mirrors: 4,
    intro: "Đích nằm ngay dưới nguồn nhưng đường thẳng bị bịt kín — dẫn tia vòng quanh cả board.",
    fixed: [
      ["source", 0, 0, "R"],
      ["receiver", 0, 8, "red"],
      ["blocker", 0, 4],
      ["blocker", 1, 1],
      ["blocker", 2, 4],
      ["blocker", 5, 2],
      ["blocker", 6, 6],
    ],
    solution: [
      [8, 0, "\\"],
      [8, 4, "/"],
      [3, 4, "/"],
      [3, 8, "/"],
    ],
  },
  {
    id: 13,
    name: "CHUỖI TÁCH",
    w: 10,
    h: 9,
    mirrors: 3,
    intro: "Hai bộ tách nối tiếp tạo THREE nhánh tia. Đưa cả ba về bộ thu.",
    fixed: [
      ["source", 0, 4, "R"],
      ["splitter", 3, 4, "\\"],
      ["splitter", 6, 4, "/"],
      ["receiver", 0, 6, "red"],
      ["receiver", 8, 7, "red"],
      ["receiver", 0, 1, "red"],
      ["blocker", 9, 4],
    ],
    solution: [
      [3, 6, "/"],
      [8, 4, "\\"],
      [6, 1, "\\"],
    ],
  },
  {
    id: 14,
    name: "SẮC HỒNG",
    w: 11,
    h: 9,
    mirrors: 2,
    intro: "Kính lọc HỒNG xuất hiện. Ba màu — ba bộ thu, đừng để nhánh nào lạc đường.",
    fixed: [
      ["source", 0, 4, "R"],
      ["splitter", 2, 4, "/"],
      ["splitter", 4, 4, "\\"],
      ["filter", 7, 4, "magenta"],
      ["receiver", 10, 4, "magenta"],
      ["filter", 6, 7, "cyan"],
      ["receiver", 10, 7, "cyan"],
      ["receiver", 5, 0, "red"],
      ["blocker", 0, 1],
    ],
    solution: [
      [2, 0, "/"],
      [4, 7, "\\"],
    ],
  },
  {
    id: 15,
    name: "BỨC TƯỜNG",
    w: 11,
    h: 9,
    mirrors: 4,
    intro: "Bức tường thép chỉ hở đúng hai khe. Chọn khe đúng — khe còn lại là bẫy.",
    fixed: [
      ["source", 0, 2, "R"],
      ["receiver", 10, 0, "red"],
      ["blocker", 5, 0],
      ["blocker", 5, 1],
      ["blocker", 5, 2],
      ["blocker", 5, 3],
      ["blocker", 5, 5],
      ["blocker", 5, 6],
      ["blocker", 5, 8],
      ["blocker", 7, 1],
    ],
    solution: [
      [2, 2, "\\"],
      [2, 4, "\\"],
      [8, 4, "/"],
      [8, 0, "/"],
    ],
  },
  {
    id: 16,
    name: "BA MÀU",
    w: 11,
    h: 10,
    mirrors: 3,
    intro: "Một nguồn, ba màu, ba bộ thu. Sắp gương để mỗi nhánh xuyên đúng kính lọc của nó.",
    fixed: [
      ["source", 0, 5, "R"],
      ["splitter", 2, 5, "\\"],
      ["splitter", 5, 5, "/"],
      ["filter", 2, 7, "cyan"],
      ["receiver", 10, 8, "cyan"],
      ["filter", 5, 2, "violet"],
      ["receiver", 10, 1, "violet"],
      ["filter", 7, 5, "magenta"],
      ["receiver", 8, 9, "magenta"],
      ["blocker", 2, 9],
    ],
    solution: [
      [2, 8, "\\"],
      [5, 1, "/"],
      [8, 5, "\\"],
    ],
  },
  {
    id: 17,
    name: "HÀNH LANG HẸP",
    w: 12,
    h: 9,
    mirrors: 4,
    intro: "Zigzag qua các hành lang hẹp giữa những khối chặn. Đếm kỹ từng hàng.",
    fixed: [
      ["source", 0, 1, "R"],
      ["receiver", 11, 5, "red"],
      ["blocker", 10, 1],
      ["blocker", 9, 4],
      ["blocker", 1, 3],
      ["blocker", 2, 6],
      ["blocker", 5, 0],
      ["blocker", 4, 7],
      ["blocker", 7, 2],
      ["blocker", 11, 0],
    ],
    solution: [
      [9, 1, "\\"],
      [9, 3, "/"],
      [2, 3, "/"],
      [2, 5, "\\"],
    ],
  },
  {
    id: 18,
    name: "GIAO LỘ",
    w: 12,
    h: 9,
    mirrors: 4,
    intro: "Hai nguồn nhuộm màu ngay từ cửa. Tia xanh và tia tím phải băng qua nhau mà không lạc đích.",
    fixed: [
      ["source", 0, 3, "R"],
      ["filter", 1, 3, "cyan"],
      ["source", 11, 6, "L"],
      ["filter", 10, 6, "violet"],
      ["receiver", 11, 0, "cyan"],
      ["receiver", 0, 8, "violet"],
      ["blocker", 9, 3],
      ["blocker", 2, 6],
      ["blocker", 5, 4],
    ],
    solution: [
      [8, 3, "/"],
      [8, 0, "/"],
      [3, 6, "/"],
      [3, 8, "/"],
    ],
  },
  {
    id: 19,
    name: "TỔ HỢP",
    w: 12,
    h: 10,
    mirrors: 3,
    intro: "Tách chùm, kính lọc và gương xoay sẵn — tất cả trong một. Bộ thu xanh ở hai đầu board.",
    fixed: [
      ["source", 0, 5, "R"],
      ["splitter", 3, 5, "\\"],
      ["filter", 5, 5, "cyan"],
      ["splitter", 7, 5, "/"],
      ["mirror", 9, 5, "/"],
      ["receiver", 9, 9, "cyan"],
      ["receiver", 0, 1, "cyan"],
      ["filter", 6, 7, "violet"],
      ["receiver", 11, 7, "violet"],
      ["blocker", 3, 9],
      ["blocker", 11, 5],
    ],
    solution: [
      [9, 5, "\\"],
      [3, 7, "\\"],
      [7, 1, "\\"],
    ],
  },
  {
    id: 20,
    name: "CHUNG KẾT 404",
    w: 12,
    h: 10,
    mirrors: 5,
    intro: "Màn cuối: 2 nguồn, 2 bộ tách, 3 kính lọc, 4 bộ thu. Dồn hết kỹ năng của bạn vào đây!",
    fixed: [
      ["source", 0, 8, "R"],
      ["splitter", 2, 8, "/"],
      ["splitter", 5, 8, "\\"],
      ["filter", 2, 4, "magenta"],
      ["filter", 7, 8, "cyan"],
      ["source", 11, 0, "L"],
      ["filter", 9, 0, "violet"],
      ["receiver", 5, 9, "red"],
      ["receiver", 9, 9, "cyan"],
      ["receiver", 5, 2, "magenta"],
      ["receiver", 4, 4, "violet"],
      ["blocker", 6, 1],
      ["blocker", 0, 3],
      ["blocker", 11, 6],
      ["blocker", 3, 3],
    ],
    solution: [
      [2, 1, "/"],
      [5, 1, "\\"],
      [9, 8, "\\"],
      [4, 0, "/"],
    ],
  },
];
